config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  get "/contact" => "pages#contact"
  get "/choix" => "pages#choix"
  get "/courses" => "pages#courses"
  get "/covoit" => "pages#covoit"
  get "/cgu" => "pages#cgu"

  resources :listes
  post "/listes/:id" => "listes#takenby"

  resources :covoiturages
  post "/covoiturages/:id" => "covoiturages#takenby"

end

app/models/liste.rb
class Liste < ApplicationRecord
  belongs_to :user

  validates :nom, presence: {message: "Nom de la liste à renseigner"}, length: { maximum: 40, too_long: "Maximum 40 caractères" }
  validates :content, presence: {message: "Contenu de la liste à renseigner"}
  validates :adresse_livraison, presence: {message: "Adresse de livraison à renseigner"}, length: { maximum: 40, too_long: "Maximum 40 caractères" }
  validates :date_livraison, presence: {message: "Date de livraison à renseigner"}
  validates :heure_livraison, presence: {message: "Heure de livraison à renseigner"}, format: { with: /\A([01]?[0-9]|2[0-3]):[0-5][0-9]\z/, message: "Heure à saisir au format HH:MM" }

  paginates_per 5

  #@listes_prises = Liste.where(takenby: current_user).order(:date_livraison)
  scope :taken_by, -> (utilisateur) { where("takenby = ? and date_livraison >= ?", utilisateur, Time.now.to_date.strftime("%Y%m%d").to_s).order(date_livraison: :asc) }
  #@listes_dispo = Liste.find_by_sql("SELECT l.* FROM listes l, users u WHERE
  #l.user_id = u.id AND l.user_id <> '#{current_user.id}' AND l.takenby = 0 AND
  #u.code_postal='#{current_user.code_postal}' AND l.date_livraison >= '#{@jour}'
  #order by l.date_livraison")
  #cope :not_taken, -> (utilisateur) { wh"user_id != ? AND takenby = ? AND date_livraison >= ?", utilisateur, 0, Time.now) }
  scope :not_taken, -> (utilisateur, code_postal) { joins(:user).where("user_id != ? and takenby = ? AND date_livraison >= ? AND users.code_postal = ?", utilisateur, 0, Time.now.to_date.strftime("%Y%m%d").to_s, code_postal).order(date_livraison: :asc) }
  scope :my_listes, -> (utilisateur) { where("user_id = ? and date_livraison >= ?", utilisateur, Time.now.to_date.strftime("%Y%m%d").to_s).order(date_livraison: :asc) }

end

app/controllers/listes_controller.rb
class ListesController < ApplicationController

  before_action :find_liste, only: [:show, :edit, :update, :destroy, :takenby]

  include SmsManagement

  def index

    @listes = Liste

    #Listes commandées par le current_user
    @listes = @listes.my_listes(current_user.id) if params[:my_listes]

    #Listes prises par le current_user
    @listes = @listes.taken_by(current_user.id) if params[:taken_by]

    #Listes disponibles
    @listes = @listes.not_taken(current_user.id, current_user.code_postal) if params[:not_taken]

    #Pagination de la liste
    @listes = @listes.page params[:page]
  end

  def show
    @id = params[:id]
  end

  def new
    @liste = Liste.new
  end

  def create
    @liste = Liste.new(liste_params)
    @liste.user = current_user
    @liste.takenby = 0
    if @liste.save
      redirect_to courses_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @liste.update(liste_params)
      redirect_to courses_path
    else
      render :edit
    end
  end

  def destroy

    @user = @liste.user

    UserMailer.liste_destroyed_email(current_user, @liste).deliver_later

    @phonenumber = format_tel(current_user.notel)
    @message = "Bestneighbor - Vous avez supprimé votre liste #{@liste.nom} pour livraison le #{@liste.date_livraison.to_date.strftime("%d %b %Y")}"
    send_sms(@phonenumber, @message)

    if @liste.takenby != 0
      @takenby = User.find(@liste.takenby)
      UserMailer.nomore_liste_email(@takenby, @liste, @user).deliver_later

      @phonenumber = format_tel(@takenby.notel)
      @message = "Bestneighbor - La liste #{@liste.nom} de #{@user.email} pour livraison le #{@liste.date_livraison.to_date.strftime("%d %b %Y")} est annulée"
      send_sms(@phonenumber, @message)
    end

    @liste.destroy
    redirect_to courses_path
  end

  def takenby

    @user = @liste.user

    if @liste.takenby != current_user.id
      @liste.takenby = current_user.id
      @cas = 1
    else
      @liste.takenby = 0
      @cas = 0
    end

    if @liste.save

      if @cas == 0
        # Envoi d'un mail au current_user et au propriétaire de la liste
        # pour indiquer qu'elle n'est plus prise en charge
        UserMailer.no_list_taken_email(@user, @liste, current_user).deliver_later
        @phonenumber = format_tel(@user.notel)
        @message = "Bestneighbor - Votre liste #{@liste.nom} n'est plus prise en charge par #{current_user.email}"
        send_sms(@phonenumber, @message)

        UserMailer.dont_take_list_email(current_user, @liste, @user).deliver_later
        @phonenumber = format_tel(current_user.notel)
        @message = "Bestneighbor - Vous ne prenez plus en charge la liste #{@liste.nom} de #{@user.email}"
        send_sms(@phonenumber, @message)
      end

      if @cas == 1
        # Envoi d'un mail au current_user et au propriétaire de la liste
        # pour indiquer qu'elle est prise en charge
        UserMailer.list_taken_email(@user, @liste, current_user).deliver_later
        @phonenumber = format_tel(@user.notel)
        @message = "Bestneighbor - Votre liste #{@liste.nom} est prise en charge par #{current_user.email}"
        send_sms(@phonenumber, @message)

        UserMailer.take_list_email(current_user, @liste, @user).deliver_later
        @phonenumber = format_tel(current_user.notel)
        @message = "Bestneighbor - Vous avez pris en charge la liste #{@liste.nom} de #{@user.email}"
        send_sms(@phonenumber, @message)
      end

      redirect_to courses_path

    end

  end

  private
  # Cette fonction permet de protéger le formulaire
  # Seules les données permises seront sauvegardées en base
  def liste_params
    params.require(:liste).permit(:nom, :content, :adresse_livraison, :date_livraison, :heure_livraison)
  end

  def find_liste
    @liste = Liste.find(params[:id])
  end

end

app/views/listes/_liste.html.erb
<div class="product">

    <div class='product-body'>
        <h6>Contenu de la liste <%= liste.nom %> : <%= liste.content %>.</h6>
        <h6>Livraison souhaitée pour le <strong><%= liste.date_livraison.to_date.strftime("%d %b %Y") %> à <%= liste.heure_livraison %></strong> à l'adresse <%= liste.adresse_livraison %></h6>
    </div>

    <ul class="list-inline product-controls">

      <% if params[:not_taken] %>
        <li>
          <%= link_to liste_path(liste, :not_taken => true), method: :takenby do %>
            <i class="fa fa-handshake-o" title="prendre en charge"></i>
          <% end %>
        </li>
      <% end %>

      <% if params[:taken_by] %>
        <li>
          <%= link_to liste_path(liste), method: :takenby do %>
            <i class="fa fa-trash" title="ne plus prendre en charge"></i>
          <% end %>
        </li>
      <% end %>

      <% if params[:my_listes] %>
        <li>
          <%= link_to liste_path(liste), method: :delete do %>
            <i class="fa fa-trash" title="supprimer"></i>
          <% end %>
        </li>
      <% end %>

    </ul>

</div>

app/views/listes/edit.html.erb
<%= content_for :title, title("Mise à jour de ma liste") %>
<%= content_for :description, description("Le contenu de la liste et la date de livraison peuvent être modifiés") %>

  <div class="container">
    <div class="spacer"></div>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">

        <%= simple_form_for @liste do |l| %>
          <%= l.input :nom, placeholder: "Nom de la liste", label: "Nom de la liste" %>
          <%= l.input :content, placeholder: "Contenu", label: "Contenu" %>
          <%= l.input :date_livraison, input_html: { class: 'date' },placeholder: "Date de livraison demandée", label: "Date de livraison demandée" %>
          <%= l.button :submit, "Enregistrer", class: "btn btn-primary" %>
        <% end %>

      </div>
    </div>
    <div class="spacer"></div>
  </div>

app/views/listes/index.html.erb
<%= content_for :title, title("Listes de courses") %>
<%= content_for :description, description("Listes de courses qui peuvent être prises en charge ou listes de courses déjà prises en charge") %>

<div class="container">

  <div class="row">

    <div class="col-xs-12 col-sm-10 col-sm-offset-1">

        <% if params[:not_taken] %>
          <h4>Prendre une liste en charge</h4>
        <% end %>

        <% if params[:taken_by] %>
          <h4>Listes prises en charge</h4>
        <% end %>

        <% if params[:my_listes] %>
          <h4>Mes listes</h4>
        <% end %>

        <%= paginate @listes %>
        <%= render @listes %>
        <%= paginate @listes %>

    </div>

  </div>

  <div class="spacer"></div>
  <% if params[:not_taken] %>
    <%= link_to "Listes prises en charge", listes_path(:taken_by => true) %>
  <% end %>

</div>

app/views/listes/new.html.erb
<%= content_for :title, title("Ma liste de courses") %>
<%= content_for :description, description("Création, modification et visualisation de ma liste de courses") %>

  <div class="container text-center">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">

        <h2>Création d'une liste</h2>
        <%= simple_form_for @liste do |l| %>

          <div class="form-inputs">
            <%= l.input :nom, input_html: { placeholder: "Nom liste" }, label: false, autofocus: true %>
            <%= l.input :content, input_html: { placeholder: "Contenu" }, label: false %>
            <%= l.input :adresse_livraison, input_html: { placeholder: "Adresse de livraison" }, label: false %>
            <%= l.input :date_livraison, input_html: { class: 'date', placeholder: "Date de livraison souhaitée" }, label: false %>
            <%= l.input :heure_livraison, input_html: { placeholder: "Heure de livraison souhaitée" }, label: false %>
          </div>

          <div class="form-actions">
            <%= l.button :submit, "Créer", class: "btn btn-primary btn-block" %>
          </div>
        <% end %>

     </div>
    </div>

  </div>

  <div class="spacer"></div>
  <%= link_to "Mes listes", listes_path(:my_listes => true) %>

app/views/listes/show.html.erb
<%= content_for :title, title("Visualisation de ma liste") %>
<%= content_for :description, description("Visualisation de l'ensemble des éléments de ma liste de courses") %>

<div class="container">

  <div class="row">

    <div class="col-xs-12 col-sm-10 col-sm-offset-1">

    <%= render @liste %>

    <div class="spacer"></div>
    <%= link_to "Retour", courses_path %>

  </div>

</div>