config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  get "/contact" => "pages#contact"
  get "/choix" => "pages#choix"
  get "/courses" => "pages#courses"
  get "/covoit" => "pages#covoit"
  get "/cgu" => "pages#cgu"

  resources :listes
  post "/listes/:id" => "listes#takenby"

  resources :covoiturages
  post "/covoiturages/:id" => "covoiturages#takenby"

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
          <div class="container text-center"> <!-- container bootstrap -->
            <div class="row">     <!-- row bootstrap -->

              <div class="col-xs-6">
                <%= link_to "Contact", contact_path, class:"navbar-wagon-item navbar-wagon-link hidden-xs" %>
                <%= link_to "Conditions générales", cgu_path, class:"navbar-wagon-item navbar-wagon-link hidden-xs" %>
              </div>

              <div class="col-xs-6">
                <ul class="list-inline social">
                  <li>
                    <a href="https://www.facebook.com/mybestneighbor/" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                  </li>

                  <li>
                    <a href="https://twitter.com/bestneighbor67" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                  </li>

                </ul>
              </div>

            </div>
          </div>
  </div>

      <!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

  <a href="/" class="navbar-wagon-brand">
    Best<strong>neighbor</strong>
  </a>

  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Covoiturage with dropdown menu -->

      <div class="navbar-wagon-item">
        <div class="dropdown">

          <a href="#" class="dropdown-toggle navbar-wagon-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Covoiturage</a>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <li>
              <%= link_to "Proposer un trajet", new_covoiturage_path %>
            </li>
            <li>
              <%= link_to "Chercher un trajet", covoiturages_path(:not_taken => true) %>
            </li>

          </ul>

        </div>
       </div>

      <!-- Courses with dropdown menu -->
      <!--

      <div class="navbar-wagon-item">
        <div class="dropdown">

          <a href="#" class="dropdown-toggle navbar-wagon-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Courses</a>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <li>
              <%= link_to "Besoin d'une course ?", new_liste_path %>
            </li>
            <li>
              <%= link_to "J'arrive à la res'course !", listes_path(:not_taken => true) %>
            </li>

          </ul>

        </div>
       </div>  -->

      <!-- Autres menus -->

      <div class="navbar-wagon-item">
        <div class="dropdown">

          <% if current_user.avatar? %>
            <%= cl_image_tag current_user.avatar.path, width: 60, height: 60, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", :data => {:toggle=>"dropdown"} %>
          <% else %>
            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", :data => {:toggle=>"dropdown"} %>
          <% end %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <li>
              <%= link_to "Mon profil", edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %>
            </li>

          </ul>

        </div>
       </div>

    <% else %>

      <div class="navbar-wagon-item">
        <div class="dropdown">

          <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", :data => {:toggle=>"dropdown"} %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <li>
              <%= link_to "Connexion", new_user_session_path %>
            </li>
            <li>
              <%= link_to "Inscription", new_user_registration_path %>
            </li>

          </ul>

        </div>
       </div>

    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-right hidden-md hidden-lg">

    <% if user_signed_in? %>

      <div class="navbar-wagon-item">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <!-- <li class="dropdown-header">Courses</li>
            <li>
              <%= link_to "Besoin d'une course ?", new_liste_path %>
            </li>
            <li>
              <%= link_to "J'arrive à la res'course !", listes_path(:not_taken => true) %>
            </li> -->

            <li class="dropdown-header">Covoiturage</li>
            <li>
              <%= link_to "Proposer un trajet", new_covoiturage_path %>
            </li>
            <li>
              <%= link_to "Chercher un trajet", covoiturages_path(:not_taken => true) %>
            </li>

          </ul>
        </div>
      </div>

      <div class="navbar-wagon-item">
        <div class="dropdown">

          <% if current_user.avatar? %>
            <%= cl_image_tag current_user.avatar.path, width: 60, height: 60, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", :data => {:toggle=>"dropdown"} %>
          <% else %>
            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", :data => {:toggle=>"dropdown"} %>
          <% end %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <li>
              <%= link_to "Mon profil", edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %>
            </li>

          </ul>

        </div>
      </div>

    <% else %>

      <div class="navbar-wagon-item">
        <div class="dropdown">

          <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", :data => {:toggle=>"dropdown"} %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to "Connexion", new_user_session_path %>
              </li>
              <li>
                <%= link_to "Inscription", new_user_registration_path %>
              </li>

            </ul>
        </div>
      </div>

    <% end %>

  </div>

</div>