config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  get "/contact" => "pages#contact"
  get "/choix" => "pages#choix"
  get "/courses" => "pages#courses"
  get "/covoit" => "pages#covoit"
  get "/cgu" => "pages#cgu"

  resources :listes
  post "/listes/:id" => "listes#takenby"

  resources :covoiturages
  post "/covoiturages/:id" => "covoiturages#takenby"

end

app/views/pages/cgu.html.erb
<%= content_for :title, title("Conditions générales d'utilisation") %>
<%= content_for :description, description("Conditions générales d'utilisation du site") %>

  <div class = "container text-left">
    <h2>Conditions générales d'utilisation</h2>
    <p>
      Le présent document a pour objet de définir les modalités et conditions dans lesquelles d’une part, bestneighbor.fr , ci-après dénommé l’EDITEUR, met à la disposition de ses utilisateurs le site, et les services disponibles sur le site et d’autre part, la manière par laquelle l’utilisateur accède au site et utilise ses services.

      Toute connexion au site est subordonnée au respect des présentes conditions.

      Pour l’utilisateur, le simple accès au site de l’EDITEUR à l’adresse URL suivante www.bestneighbor.fr implique l’acceptation de l’ensemble des conditions décrites ci-après.
    </p>

    <h3>Propriété intellectuelle</h3>
    <p>
      Aucune reproduction, même partielle prévue à l’article L.122-5 du Code de la propriété intellectuelle, ne peut être faite de ce site sans l’autorisation du directeur de publication.
    </p>

    <h3>Liens hypertextes</h3>
    <p>
      Le site www. bestneighbor.fr peut contenir des liens hypertextes vers d’autres sites présents sur le réseau Internet. Les liens vers ces autres ressources vous font quitter le site www.bestneighbor.fr

      Il est possible de créer un lien vers la page de présentation de ce site sans autorisation expresse de l’EDITEUR. Aucune autorisation ou demande d’information préalable ne peut être exigée par l’éditeur à l’égard d’un site qui souhaite établir un lien vers le site de l’éditeur. Il convient toutefois d’afficher ce site dans une nouvelle fenêtre du navigateur. Cependant, l’EDITEUR se réserve le droit de demander la suppression d’un lien qu’il estime non conforme à l’objet du site www.bestneighbor.fr
    </p>

    <h3>Responsabilité de l’éditeur</h3>
    <p>
      Les informations et/ou documents figurant sur ce site et/ou accessibles par ce site proviennent de sources considérées comme étant fiables.

      Toutefois, ces informations et/ou documents sont susceptibles de contenir des inexactitudes techniques et des erreurs typographiques.

      L’EDITEUR se réserve le droit de les corriger, dès que ces erreurs sont portées à sa connaissance.

      Il est fortement recommandé de vérifier l’exactitude et la pertinence des informations et/ou documents mis à disposition sur ce site.

      Les informations et/ou documents disponibles sur ce site sont susceptibles d’être modifiés à tout moment, et peuvent avoir fait l’objet de mises à jour. En particulier, ils peuvent avoir fait l’objet d’une mise à jour entre le moment de leur téléchargement et celui où l’utilisateur en prend connaissance.

      L’utilisation des informations et/ou documents disponibles sur ce site se fait sous l’entière et seule responsabilité de l’utilisateur, qui assume la totalité des conséquences pouvant en découler, sans que l’EDITEUR puisse être recherché à ce titre, et sans recours contre ce dernier.

      L’EDITEUR ne pourra en aucun cas être tenu responsable de tout dommage de quelque nature qu’il soit résultant de l’interprétation ou de l’utilisation des informations et/ou documents disponibles sur ce site.
    </p>

    <h3>Accès au site</h3>
    <p>
      L’éditeur s’efforce de permettre l’accès au site 24 heures sur 24, 7 jours sur 7, sauf en cas de force majeure ou d’un événement hors du contrôle de l’EDITEUR, et sous réserve des éventuelles pannes et interventions de maintenance nécessaires au bon fonctionnement du site et des services.

      Par conséquent, l’EDITEUR ne peut garantir une disponibilité du site et/ou des services, une fiabilité des transmissions et des performances en terme de temps de réponse ou de qualité. Il n’est prévu aucune assistance technique vis à vis de l’utilisateur que ce soit par des moyens électronique ou téléphonique.

      La responsabilité de l’éditeur ne saurait être engagée en cas d’impossibilité d’accès à ce site et/ou d’utilisation des services.

      Par ailleurs, l’EDITEUR peut être amené à interrompre le site ou une partie des services, à tout moment sans préavis, le tout sans droit à indemnités. L’utilisateur reconnaît et accepte que l’EDITEUR ne soit pas responsable des interruptions, et des conséquences qui peuvent en découler pour l’utilisateur ou tout tiers.
    </p>

    <h3>Modification des conditions d’utilisation</h3>
    <p>
      L’EDITEUR se réserve la possibilité de modifier, à tout moment et sans préavis, les présentes conditions d’utilisation afin de les adapter aux évolutions du site et/ou de son exploitation.
    </p>

    <h3>Règles d'usage d'Internet</h3>
    <p>
      L’utilisateur déclare accepter les caractéristiques et les limites d’Internet, et notamment reconnaît que :

      L’EDITEUR n’assume aucune responsabilité sur les services accessibles par Internet et n’exerce aucun contrôle de quelque forme que ce soit sur la nature et les caractéristiques des données qui pourraient transiter par l’intermédiaire de son centre serveur.

      L’utilisateur reconnaît que les données circulant sur Internet ne sont pas protégées notamment contre les détournements éventuels. La présence du logo   ____  institue une présomption simple de validité. La communication de toute information jugée par l’utilisateur de nature sensible ou confidentielle se fait à ses risques et périls.

      L’utilisateur reconnaît que les données circulant sur Internet peuvent être réglementées en termes d’usage ou être protégées par un droit de propriété.

      L’utilisateur est seul responsable de l’usage des données qu’il consulte, interroge et transfère sur Internet.

      L’utilisateur reconnaît que l’EDITEUR ne dispose d’aucun moyen de contrôle sur le contenu des services accessibles sur Internet
    </p>

    <h3>Droit applicable</h3>
    <p>
      Tant le présent site que les modalités et conditions de son utilisation sont régis par le droit français, quel que soit le lieu d’utilisation. En cas de contestation éventuelle, et après l’échec de toute tentative de recherche d’une solution amiable, les tribunaux français seront seuls compétents pour connaître de ce litige.

      Pour toute question relative aux présentes conditions d’utilisation du site, vous pouvez nous écrire à l’adresse suivante : contact@bestneighbor.fr
    </p>


    <h2>Inscription</h2>
    <!-- <p>La saisie du code postal est demandée pour permettre de
    proposer les trajets ou les listes de courses de voisins inscrits
    avec le même code postal que vous</p> -->
    <p>La saisie du code postal est demandée pour permettre de
    proposer les trajets de voisins inscrits
    avec le même code postal que vous</p>

    <h2>Covoiturage</h2>
    <p>"Proposer un trajet" : permet de créer un trajet qui
    pourra être réservé par des voisins inscrits avec le <strong>même code postal que vous</strong></p>
    <p>"Chercher un trajet" : permet de visualiser et réserver un trajet proposé
    par un voisin inscrit avec le <strong>même code postal que vous</strong></p>

    <!-- <h2>Courses</h2>
    <p>"Besoin d'une course ?" : permet de créer une liste de courses qui
    pourra être prise en charge par un voisin inscrit avec le <strong>même code postal que vous</strong></p>
    <p>"J'arrive à la res'course !" : permet de prendre en chareg une liste de courses
    créée par un voisin inscrit avec le <strong>même code postal que vous</strong></p> -->
  </div>

app/views/pages/contact.html.erb
  <%= content_for :title, title("Aide") %>
  <%= content_for :description, description("Description du fonctionnement du covoiturage") %>

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "city-2042634_960_720.png" %>');">

  <div class="banner-content">

    <div class="container text-center detail">

          <div class="row">

            <h2>Nous sommes à votre disposition pour répondre à vos questions</h2>

          </div>

          <div class="spacer"></div>

          <div class="row">

            <p>Vous pouvez nous joindre par email en écrivant à l'adresse <strong>contact@bestneighbor.fr</strong></p>

          </div>

    </div>
  </div>
</div>

app/views/pages/courses.html.erb
<%= content_for :title, title("Courses") %>
<%= content_for :description, description("Actions possibles pour les courses") %>

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "shopping-cart-304843_960_720.png" %>');">

  <div class="banner-content">

      <div class="container text-center">

          <div class="row">
            <h2>Courses</h2>
          </div>

          <div class="row">

            <div class="col-sm-6 col-md-6 feature circle">
              <%= link_to "Besoin d'une course ?", new_liste_path, class: "btn btn-primary btn-lg" %>
            </div>

            <br>

            <div class="col-sm-6 col-md-6 feature circle">
              <%= link_to "J'arrive à la res'course !", listes_path(:not_taken => true), class: "btn btn-primary btn-lg" %>
            </div>

          </div>

      </div>

  </div>

</div>

app/views/pages/covoit.html.erb
<%= content_for :title, title("Covoiturage") %>
<%= content_for :description, description("Actions possibles pour le covoiturage") %>

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "carpooling-32719_960_720.png" %>');">

    <div class="banner-content">

      <div class="container text-center">

          <div class="row">
            <h2>Covoiturage</h2>
          </div>

          <div class="row">

            <div class="col-sm-6 col-md-6 feature circle">
              <%= link_to "Proposer un trajet", new_covoiturage_path, class: "btn btn-warning btn-lg" %>
            </div>

            <br>

            <div class="col-sm-6 col-md-6 feature circle">
              <%= link_to "Chercher un trajet", covoiturages_path(:not_taken => true), class: "btn btn-warning btn-lg" %>
            </div>

          </div>

      </div>

  </div>
</div>

app/views/pages/home.html.erb
<%= content_for :title, title("Accueil") %>
<%= content_for :description, description("Covoiturage entre voisins - connexion et inscription depuis cette page") %>


<!--<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "city-2042634_960_720.png" %>');">-->
<div class="banner" style="background-image: url('<%= image_path "city-2042634_960_720.png" %>');">
  <div class="banner-content">

    <div class="container text-center">
      <div class="row">

        <% if user_signed_in? %>

          <!--<%= link_to "Covoiturage", covoit_path, class: "btn btn-primary btn-lg" %>
          <div class="spacer"></div>-->

          <!--
          <%= link_to "Courses", courses_path, class: "btn btn-primary btn-lg" %>
          <div class="spacer"></div>
          -->

          <% if @neighbors === 0 %>
            <p class="nbvoisins"><strong>Vous n'avez pas encore de voisins inscrits près de chez vous</strong></p>
            <p class="info"><strong><em>Parlez en autour de vous !</strong></em></p>
          <% elsif @neighbors === 1 %>
            <p class="nbvoisins"><strong><%= @neighbors %> voisin est inscrit près de chez vous<strong></p>
            <p class="info"><strong><em>Pour avoir plus de voisins parlez en autour de vous !</strong></em></p>
          <% elsif @neighbors < 20 %>
            <p class="nbvoisins"><strong><%= @neighbors %> voisins sont déjà inscrits près de chez vous</strong></p>
            <p class="info"><strong><em>Pour avoir plus de voisins parlez en autour de vous !<strong></em></p>
          <% end %>

          <!--<%= link_to "Déconnexion", destroy_user_session_path, method: :delete %>-->

        <% else %>

          <h2>Covoiturage entre voisins !</h2>
          <div class="spacer"></div>
          <div class="spacer"></div>
          <div class="spacer"></div>
          <!--<h4>Vous voulez donner un coup de main ou être dépanné ?</h4>-->
          <%= link_to "Démarrer", new_user_registration_path, class: "btn btn-warning btn-lg" %>

        <% end %>

      </div>

    </div>
  </div>
</div>

<div class="spacer"></div>

<!--
<div class="banner-content">

  <div class="container text-center detail">

        <div class="spacer"></div>

        <div class="row">

            <h4>Courses ... </h4>
            <h5>comment ça marche ?</h5>

        </div>

        <div class="spacer"></div>

        <div class="row">

          <div class="col-sm-4 col-md-4 feature">
            <%= image_tag "noun_656300_cc.png", alt: "Créer liste de courses", title: "Créer liste de courses", width: "75" %>
            <p></p>
            <h6>Je <strong>crée</strong> ma liste de courses ...</h6>
          </div>

          <div class="col-sm-4 col-md-4 feature">
            <%= image_tag "noun_556101_cc.png", alt: "Mail", title: "Mail", width: "75" %>
            <p></p>
            <h6>lorsqu'un voisin la prend en charge lui et moi recevons un <strong>mail</strong> et un <strong>SMS</strong> ...</h6>
          </div>

          <div class="col-sm-4 col-md-4 feature">
            <%= image_tag "noun_602639_cc.png", alt: "Contact", title: "Contact", width: "75" %>
            <p></p>
            <h6>nous pouvons nous <strong>contacter</strong> !</h6>
          </div>

        </div>

    </div>
  </div>
-->

<!-- <div class="separation6"></div> -->

<div class="banner-content">

  <div class="container text-center detail">

        <div class="spacer"></div>

        <div class="row">

            <!-- <h4>Covoiturage ... </h4> -->
            <h4>Comment ça marche ?</h4>

        </div>

        <div class="spacer"></div>

        <div class="row">

          <div class="col-sm-4 col-md-4 feature ">
            <%= image_tag "noun_232814_cc.png", alt: "Chercher trajet", title: "Chercher trajet", width: "75" %>
            <p></p>
            <h6>Je <strong>cherche</strong> un trajet proposé par un voisin et je <strong>réserve</strong> ...</h6>
          </div>

          <div class="col-sm-4 col-md-4 feature">
            <%= image_tag "noun_556101_cc.png", alt: "Mail", title: "Mail", width: "75" %>
            <p></p>
            <h6>mon voisin et moi recevons un <strong>mail</strong> et un <strong>SMS</strong> ...</h6>
          </div>

          <div class="col-sm-4 col-md-4 feature">
            <%= image_tag "noun_602639_cc.png", alt: "Contact", title: "Contact", width: "75" %>
            <p></p>
            <h6>nous pouvons nous <strong>contacter</strong> !</h6>
          </div>

        </div>

  </div>
</div>

app/views/pages/robots.txt.erb
<% if Rails.env.production? %>
  User-Agent: *
  Allow: /
  Disallow: /admin
<% else %>
  User-Agent: *
  Disallow: /
<% end %>

app/views/pages/team.html.erb
<div class = "container text-center">
  <h1>"Meet the team"</h1>"
</div>