config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  get "/contact" => "pages#contact"
  get "/choix" => "pages#choix"
  get "/courses" => "pages#courses"
  get "/covoit" => "pages#covoit"
  get "/cgu" => "pages#cgu"

  resources :listes
  post "/listes/:id" => "listes#takenby"

  resources :covoiturages
  post "/covoiturages/:id" => "covoiturages#takenby"

end

app/models/covoiturage.rb
class Covoiturage < ApplicationRecord

  belongs_to :user

  validates :destination, presence: {message: "Destination à renseigner"}, length: { maximum: 40, too_long: "Maximum 40 caractères" }
  validates :date, presence: {message: "Date à préciser"}
  validates :heure, presence: {message: "Heure à préciser"}, format: { with: /\A([01]?[0-9]|2[0-3]):[0-5][0-9]\z/, message: "Heure à saisir au format HH:MM" }
  #validates :heure, presence: {message: "Heure à préciser"}
  validates :nbplaces, presence: {message: "Nombre de places proposées à renseigner : 1, 2 ou 3"}, inclusion: {in: [1, 2, 3], message: "Nombre de places proposées à renseigner : 1, 2 ou 3"}
  validates :depart, presence: {message: "Lieu de départ à renseigner"}, length: { maximum: 40, too_long: "Maximum 40 caractères" }
  #validates :nbpass1, presence: {message: "Nombre de places à réserver à renseigner : 1, 2 ou 3"}, inclusion: {in: [1, 2, 3]}
  #validates :nbpass2, presence: {message: "Nombre de places à réserver à renseigner : 1, 2 ou 3"}, inclusion: {in: [1, 2, 3]}
  #validates :nbpass3, presence: {message: "Nombre de places à réserver à renseigner : 1, 2 ou 3"}, inclusion: {in: [1, 2, 3]}

  paginates_per 5

  #@trajets_pris = Trajet.where(takenby: current_user).order(:date)
  scope :taken_by, -> (utilisateur) { where("(takenby1 = ? or takenby2 = ? or takenby3 = ?) and date >= ?", utilisateur, utilisateur, utilisateur, Time.now.to_date.strftime("%Y%m%d").to_s).order(date: :asc) }
  #@trajets_dispo = Trajet.find_by_sql("SELECT t.* FROM trajets t, users u WHERE
  #    t.user_id = u.id AND t.user_id <> '#{current_user.id}' AND t.takenby = 0 AND
  #    u.code_postal='#{current_user.code_postal}' AND t.date >= '#{@jour}'
  #    order by t.date")
  scope :not_taken, -> (utilisateur, code_postal) { joins(:user).where("user_id != ? AND takenby1 != ? AND takenby2 != ? AND takenby3 != ? and nbdispos > ? AND date >= ? AND users.code_postal = ?", utilisateur, utilisateur, utilisateur, utilisateur, 0, Time.now.to_date.strftime("%Y%m%d").to_s, code_postal).order(date: :asc) }
  scope :my_covoits, -> (utilisateur) { where("user_id = ? and date >= ?", utilisateur, Time.now.to_date.strftime("%Y%m%d").to_s).order(date: :asc) }

end

app/controllers/covoiturages_controller.rb
class CovoituragesController < ApplicationController

  before_action :find_covoiturage, only: [:show, :edit, :update, :destroy, :takenby]

  include SmsManagement

  def index
    @covoiturages = Covoiturage

    #Trajets proposés par le current_user
    @covoiturages = @covoiturages.my_covoits(current_user.id) if params[:my_covoits]

    #Trajets réservés par le current_user
    @covoiturages = @covoiturages.taken_by(current_user.id) if params[:taken_by]

    #Trajets proposés disponibles
    @covoiturages = @covoiturages.not_taken(current_user.id, current_user.code_postal) if params[:not_taken]

    #Pagination des trajets
    @covoiturages = @covoiturages.page params[:page]
  end

  def show
    @id = params[:id]
  end

  def new
    @cov = Covoiturage.new
  end

  def create
    @cov = Covoiturage.new(covoiturage_params)
    @cov.user = current_user
    @cov.takenby1 = 0
    @cov.nbpass1 = 0
    @cov.takenby2 = 0
    @cov.nbpass2 = 0
    @cov.takenby3 = 0
    @cov.nbpass3 = 0
    @cov.nbdispos = @cov.nbplaces
    if @cov.save
      flash[:notice] = "Votre proposition de trajet est créée"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit

  end

  def update

    @cas1 = @cas2 = @cas3 = false
    @cas = 0

    if @cov.user != current_user
      if (@cov.takenby1 != current_user.id and @cov.takenby1 === 0)
        @cov.takenby1 = current_user.id
        @cas1 = true
      elsif (@cov.takenby2 != current_user.id and @cov.takenby2 === 0)
        @cov.takenby2 = current_user.id
        @cas2 = true
      elsif (@cov.takenby3 != current_user.id and @cov.takenby3 === 0)
        @cov.takenby3 = current_user.id
        @cas3 = true
        end
    end

    if @cov.update(covoiturage_params)

      @user = @cov.user

      if @cas1
        (@cov.nbpass1 === nil) ? (@cov.nbpass1 = 1) : (@cov.nbpass1 = @cov.nbpass1)
        @cov.nbdispos = @cov.nbdispos - @cov.nbpass1
        @cas = 1
        @smsnbpass = @cov.nbpass1
        @cov.save
      elsif @cas2
        (@cov.nbpass2 === nil) ? (@cov.nbpass2 = 1) : (@cov.nbpass2 = @cov.nbpass2)
        @cov.nbdispos = @cov.nbdispos - @cov.nbpass2
        @cas = 2
        @smsnbpass = @cov.nbpass2
        @cov.save
      elsif @cas3
        (@cov.nbpass3 === nil) ? (@cov.nbpass3 = 1) : (@cov.nbpass3 = @cov.nbpass3)
        @cov.nbdispos = @cov.nbdispos - @cov.nbpass3
        @cas = 3
        @smsnbpass = @cov.nbpass3
        @cov.save
      end


#########################################################
# Envoi mails et SMS
      UserMailer.covoiturage_taken_email(@user, @cov, current_user, @cas).deliver_later

      @phonenumber = format_tel(@user.notel)
      @message = "Bestneighbor - Votre trajet du #{@cov.date.to_date.strftime("%d %b %Y")} à #{@cov.heure} est réservé par #{current_user.email}"
      send_sms(@phonenumber, @message)

      UserMailer.take_covoiturage_email(current_user, @cov, @user, @cas).deliver_later

      @phonenumber = format_tel(current_user.notel)
      @message = "Bestneighbor - Vous avez réservé #{@smsnbpass} place(s) pour le trajet de #{@user.email} du #{@cov.date.to_date.strftime("%d %b %Y")} à #{@cov.heure}"
      send_sms(@phonenumber, @message)

############################################################

      flash[:notice] = "Votre réservation de trajet est faite"
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy

    @user = @cov.user

    UserMailer.covoiturage_destroyed_email(current_user, @cov).deliver_later

    @phonenumber = format_tel(current_user.notel)
    @message = "Bestneighbor - Vous avez supprimé votre proposition de trajet du #{@cov.date.to_date.strftime("%d %b %Y")} à #{@cov.heure}"
    send_sms(@phonenumber, @message)

    if @cov.takenby1 != 0
      @takenby1 = User.find(@cov.takenby1)
      UserMailer.nomore_covoiturage_email(@takenby1, @cov, @user).deliver_later

      @phonenumber = format_tel(@takenby1.notel)
      @message = "Bestneighbor - Le trajet proposé par #{@user.email} du #{@cov.date.to_date.strftime("%d %b %Y")} à #{@cov.heure} est annulé"
      send_sms(@phonenumber, @message)
    end

    if @cov.takenby2 != 0
      @takenby2 = User.find(@cov.takenby2)
      UserMailer.nomore_covoiturage_email(@takenby2, @cov, @user).deliver_later

      @phonenumber = format_tel(@takenby2.notel)
      @message = "Bestneighbor - Le trajet proposé par #{@user.email} du #{@cov.date.to_date.strftime("%d %b %Y")} à #{@cov.heure} est annulé"
      send_sms(@phonenumber, @message)
    end

    if @cov.takenby3 != 0
      @takenby3 = User.find(@cov.takenby3)
      UserMailer.nomore_covoiturage_email(@takenby3, @cov, @user).deliver_later

      @phonenumber = format_tel(@takenby3.notel)
      @message = "Bestneighbor - Le trajet proposé par #{@user.email} du #{@cov.date.to_date.strftime("%d %b %Y")} à #{@cov.heure} est annulé"
      send_sms(@phonenumber, @message)
    end

    @cov.destroy
    flash[:notice] = "Votre proposition de trajet est supprimée"
    redirect_to root_path
  end

  def takenby

    @user = @cov.user
    @cas = 0

    if @cov.takenby1 === current_user.id
      @cov.takenby1 = 0
      @cov.nbdispos = @cov.nbdispos + @cov.nbpass1
      @smsnbpass = @cov.nbpass1
      @cov.nbpass1 = 0
      @cas = 1
    elsif @cov.takenby2 === current_user.id
      @cov.takenby2 = 0
      @cov.nbdispos = @cov.nbdispos + @cov.nbpass2
      @smsnbpass = @cov.nbpass2
      @cov.nbpass2 = 0
      @cas = 2
    elsif @cov.takenby3 === current_user.id
      @cov.takenby3 = 0
      @cov.nbdispos = @cov.nbdispos + @cov.nbpass3
      @smsnbpass = @cov.nbpass3
      @cov.nbpass3 = 0
      @cas = 3
    end

    if @cov.save

#########################################################
# Envoi mails et SMS
      UserMailer.no_covoiturage_taken_email(@user, @cov, current_user, @cas).deliver_later

      @phonenumber = format_tel(@user.notel)
      @message = "Bestneighbor - Votre trajet du #{@cov.date.to_date.strftime("%d %b %Y")} à #{@cov.heure} n'est plus réservé par #{current_user.email}"
      send_sms(@phonenumber, @message)

      UserMailer.dont_take_covoiturage_email(current_user, @cov, @user, @cas).deliver_later

      @phonenumber = format_tel(current_user.notel)
      @message = "Bestneighbor - Vous avez annulé votre réservation de #{@smsnbpass} place(s) pour le trajet de #{@user.email} du #{@cov.date.to_date.strftime("%d %b %Y")} à #{@cov.heure}"
      send_sms(@phonenumber, @message)

############################################################

      flash[:notice] = "Votre réservation est annulée"
      redirect_to root_path

    end
  end

  private
  # Cette fonction permet de protéger le formulaire
  # Seules les données permises seront sauvegardées en base
  def covoiturage_params
    params.require(:covoiturage).permit(:destination, :date, :heure, :nbplaces, :depart, :takenby1, :nbpass1, :takenby2, :nbpass2, :takenby3, :nbpass3)
  end

  def find_covoiturage
    @cov = Covoiturage.find(params[:id])
  end

end

app/helpers/covoiturages_helper.rb
module CovoituragesHelper
end

app/views/covoiturages/_covoiturage.html.erb
<div class="product">

      <div class='product-body'>
        <h6>Au départ de <strong><%= covoiturage.depart %></strong> pour <strong><%= covoiturage.destination %></strong></h6>
        <h6>Le <strong><%= covoiturage.date.to_date.strftime("%d %b %Y") %> à <%= covoiturage.heure %></strong></h6>
        <% if params[:my_covoits] or params[:not_taken] %>
          <h6>Places proposées : <%= covoiturage.nbplaces %></h6>
          <h6>Places restantes : <%= covoiturage.nbdispos %></h6>
        <% end %>
      </div>

      <ul class="list-inline product-controls">

      <% if params[:not_taken] %>
        <li>
          <%= link_to edit_covoiturage_path(covoiturage, :not_taken => true) do %>
            <i class="fa fa-handshake-o" title="réserver"></i>
          <% end %>
        </li>
      <% end %>

      <% if params[:taken_by] %>
        <li>
          <%= link_to covoiturage_path(covoiturage), method: :takenby do %>
            <i class="fa fa-trash" title="ne plus réserver"></i>
          <% end %>
        </li  >
      <% end %>

      <% if params[:my_covoits] %>
        <li>
          <%= link_to covoiturage_path(covoiturage), method: :delete do %>
            <i class="fa fa-trash" title="supprimer"></i>
          <% end %>
        </li>
      <% end %>

    </ul>

</div>

app/views/covoiturages/edit.html.erb
<%= content_for :title, title("Saisie du nombre de passagers") %>
<%= content_for :description, description("Pour l'instant on propose un seul passager par réservation") %>

  <div class="container">
    <div class="spacer"></div>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">

        <% if params[:not_taken] %>

          <%= simple_form_for @cov do |t| %>
            <%= t.input :destination, placeholder: "Destination", label: "Destination", disabled: true, :as => :hidden %>
            <%= t.input :depart, placeholder: "Départ", label: "Départ", disabled: true, :as => :hidden %>
            <%= t.input :date, input_html: { class: 'date' },placeholder: "Date", label: "Date", disabled: true, :as => :hidden %>
            <%= t.input :heure, placeholder: "Heure", label: "Heure", disabled: true, :as => :hidden %>
            <%= t.input :nbdispos, placeholder: "Places disponibles", label: "Places disponibles", disabled: true, :as => :hidden %>

            <% if @cov.nbpass1 === 0 and @cov.nbdispos === 3 %>
              <%= t.input :nbpass1, collection: ["1", "2", "3"], placeholder: "Places à réserver", label: "Places à réserver" %>
            <% elsif @cov.nbpass1 === 0 and @cov.nbdispos === 2 %>
              <%= t.input :nbpass1, collection: ["1", "2"], placeholder: "Places à réserver", label: "Places à réserver" %>
            <% elsif @cov.nbpass1 === 0 and @cov.nbdispos === 1 %>
              <%= t.input :nbpass1, collection: ["1"], placeholder: "Places à réserver", label: "Places à réserver" %>
            <% elsif @cov.nbpass2 === 0 and @cov.nbdispos === 3 %>
              <%= t.input :nbpass2, collection: ["1", "2", "3"], placeholder: "Places à réserver", label: "Places à réserver" %>
            <% elsif @cov.nbpass2 === 0 and @cov.nbdispos === 2 %>
              <%= t.input :nbpass2, collection: ["1", "2"], placeholder: "Places à réserver", label: "Places à réserver" %>
            <% elsif @cov.nbpass2 === 0 and @cov.nbdispos === 1 %>
              <%= t.input :nbpass2, collection: ["1"], placeholder: "Places à réserver", label: "Places à réserver" %>
            <% elsif @cov.nbpass3 === 0 and @cov.nbdispos === 3 %>
              <%= t.input :nbpass3, collection: ["1", "2", "3"], placeholder: "Places à réserver", label: "Places à réserver" %>
            <% elsif @cov.nbpass3 === 0 and @cov.nbdispos === 2 %>
              <%= t.input :nbpass3, collection: ["1", "2"], placeholder: "Places à réserver", label: "Places à réserver" %>
            <% elsif @cov.nbpass3 === 0 and @cov.nbdispos === 1 %>
              <%= t.input :nbpass3, collection: ["1"], placeholder: "Places à réserver", label: "Places à réserver" %>
            <% end %>

            <%= t.button :submit, "Enregistrer", class: "btn btn-warning" %>
          <% end %>

        <% else %>

          <%= simple_form_for @cov do |t| %>
            <%= t.input :destination, placeholder: "Destination", label: "Destination" %>
            <%= t.input :depart, placeholder: "Départ", label: "Départ" %>
            <%= t.input :date, input_html: { class: 'date' },placeholder: "Date", label: "Date" %>
            <%= t.input :heure, placeholder: "Heure", label: "Heure" %>
            <%= t.input :nbplaces, placeholder: "Places proposées", label: "Places proposées", disabled: true %>
            <%= t.input :nbdispos, placeholder: "Places disponibles", label: "Places disponibles", disabled: true %>
            <%= t.button :submit, "Enregistrer", class: "btn btn-warning" %>
          <% end %>

        <% end %>

      </div>
    </div>
    <div class="spacer"></div>
  </div>

app/views/covoiturages/index.html.erb
<%= content_for :title, title("Listes de trajets") %>
<%= content_for :description, description("Listes de trajets à chercher, choisis ou proposés") %>

<div class="container">

  <div class="row">

    <div class="col-xs-12 col-sm-10 col-sm-offset-1">

      <% if params[:not_taken] %>
        <h4>Trajets disponibles</h4>
      <% end %>

      <% if params[:taken_by] %>
        <h4>Mes trajets réservés</h4>
      <% end %>

      <% if params[:my_covoits] %>
        <h4>Mes propositions</h4>
      <% end %>

      <%= paginate @covoiturages %>
      <%= render @covoiturages %>
      <%= paginate @covoiturages %>

     </div>

  </div>

  <div class="spacer"></div>
  <% if params[:not_taken] %>
    <%= link_to "Mes trajets réservés", covoiturages_path(:taken_by => true) %>
  <% end %>

</div>

app/views/covoiturages/new.html.erb
<%= content_for :title, title("Proposer un nouveau trajet") %>
<%= content_for :description, description("Création d'une proposition de trajet") %>

  <div class="container text-center">
     <div class="row">
      <div class="col-sm-4 col-sm-offset-4">

        <h2>Création d'un trajet</h2>
        <%= simple_form_for @cov do |t| %>

          <div class="form-inputs">
            <%= t.input :depart, input_html: { placeholder: "Départ" }, label: false, autofocus: true %>
            <%= t.input :destination, input_html: { placeholder: "Destination" }, label: false %>
            <%= t.input :date, input_html: { class: 'date', placeholder: "Date départ" },label: false %>
            <%= t.input :heure, input_html: { placeholder: "Heure de départ" }, label: false %>
            <%= t.input :nbplaces, input_html: { placeholder: "Nb de places proposées" }, label: false %>
          </div>

          <div class="form-actions">
            <%= t.button :submit, "Créer", class: "btn btn-warning btn-block" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>

  <div class="spacer"></div>
  <%= link_to "Mes propositions", covoiturages_path(:my_covoits => true) %>

app/views/covoiturages/show.html.erb
<%= content_for :title, title("Visualisation des trajets sélectionnés") %>
<%= content_for :description, description("Visualisation de l'ensemble des informations liées aux trajets") %>

<div class="container">

  <div class="row">

    <div class="col-xs-12 col-sm-10 col-sm-offset-1">

    <%= render @covoiturage %>

    <div class="spacer"></div>
    <%= link_to "Retour", covoit_path %>

     </div>

  </div>